"""
BRep primitive shapes
"""
from __future__ import annotations
import mod3d.Geom
import mod3d.Geom2d
import mod3d.TopoDS
import mod3d.gp
import typing
__all__: list[str] = ['Builder', 'OneAxis', 'Revolution']
class Builder:
    @typing.overload
    def __init__(self) -> None:
        ...
    @typing.overload
    def __init__(self, B: BRep_Builder) -> None:
        ...
    def add_edge_vertex(self, E: mod3d.TopoDS.Edge, V: mod3d.TopoDS.Vertex, P: typing.SupportsFloat, direct: bool) -> None:
        ...
    def add_edge_vertex_closed(self, E: mod3d.TopoDS.Edge, V: mod3d.TopoDS.Vertex, P1: typing.SupportsFloat, P2: typing.SupportsFloat) -> None:
        ...
    def add_face_wire(self, F: mod3d.TopoDS.Face, W: mod3d.TopoDS.Wire) -> None:
        ...
    def add_shell_face(self, Sh: mod3d.TopoDS.Shell, F: mod3d.TopoDS.Face) -> None:
        ...
    def add_wire_edge(self, W: mod3d.TopoDS.Wire, E: mod3d.TopoDS.Edge, direct: bool) -> None:
        ...
    def builder(self) -> BRep_Builder:
        ...
    def complete_edge(self, E: mod3d.TopoDS.Edge) -> None:
        ...
    def complete_face(self, F: mod3d.TopoDS.Face) -> None:
        ...
    def complete_shell(self, S: mod3d.TopoDS.Shell) -> None:
        ...
    def complete_wire(self, W: mod3d.TopoDS.Wire) -> None:
        ...
    def make_degenerated_edge(self) -> mod3d.TopoDS.Edge:
        ...
    @typing.overload
    def make_edge(self, line: mod3d.gp.Lin) -> mod3d.TopoDS.Edge:
        ...
    @typing.overload
    def make_edge(self, circle: mod3d.gp.Circ) -> mod3d.TopoDS.Edge:
        ...
    def make_face(self, plane: mod3d.gp.Pln) -> mod3d.TopoDS.Face:
        ...
    def make_shell(self) -> mod3d.TopoDS.Shell:
        ...
    def make_vertex(self, point: mod3d.gp.Pnt) -> mod3d.TopoDS.Vertex:
        ...
    def make_wire(self) -> mod3d.TopoDS.Wire:
        ...
    def reverse_face(self, F: mod3d.TopoDS.Face) -> None:
        ...
    def set_parameters(self, E: mod3d.TopoDS.Edge, V: mod3d.TopoDS.Vertex, P1: typing.SupportsFloat, P2: typing.SupportsFloat) -> None:
        ...
    @typing.overload
    def set_pcurve(self, E: mod3d.TopoDS.Edge, F: mod3d.TopoDS.Face, L: mod3d.gp.Lin2d) -> None:
        ...
    @typing.overload
    def set_pcurve(self, E: mod3d.TopoDS.Edge, F: mod3d.TopoDS.Face, L1: mod3d.gp.Lin2d, L2: mod3d.gp.Lin2d) -> None:
        ...
    @typing.overload
    def set_pcurve(self, E: mod3d.TopoDS.Edge, F: mod3d.TopoDS.Face, C: mod3d.gp.Circ2d) -> None:
        ...
class OneAxis:
    @typing.overload
    def angle(self) -> float:
        ...
    @typing.overload
    def angle(self, a: typing.SupportsFloat) -> None:
        ...
    @typing.overload
    def axes(self) -> mod3d.gp.Ax2:
        ...
    @typing.overload
    def axes(self, a: mod3d.gp.Ax2) -> None:
        ...
    def axis_bottom_vertex(self) -> mod3d.TopoDS.Vertex:
        ...
    def axis_edge(self) -> mod3d.TopoDS.Edge:
        ...
    def axis_end_wire(self) -> mod3d.TopoDS.Wire:
        ...
    def axis_start_wire(self) -> mod3d.TopoDS.Wire:
        ...
    def axis_top_vertex(self) -> mod3d.TopoDS.Vertex:
        ...
    def bottom_edge(self) -> mod3d.TopoDS.Edge:
        ...
    def bottom_end_vertex(self) -> mod3d.TopoDS.Vertex:
        ...
    def bottom_face(self) -> mod3d.TopoDS.Face:
        ...
    def bottom_start_vertex(self) -> mod3d.TopoDS.Vertex:
        ...
    def bottom_wire(self) -> mod3d.TopoDS.Wire:
        ...
    def end_bottom_edge(self) -> mod3d.TopoDS.Edge:
        ...
    def end_edge(self) -> mod3d.TopoDS.Edge:
        ...
    def end_face(self) -> mod3d.TopoDS.Face:
        ...
    def end_top_edge(self) -> mod3d.TopoDS.Edge:
        ...
    def end_wire(self) -> mod3d.TopoDS.Wire:
        ...
    def has_bottom(self) -> bool:
        ...
    def has_sides(self) -> bool:
        ...
    def has_top(self) -> bool:
        ...
    def lateral_end_wire(self) -> mod3d.TopoDS.Wire:
        ...
    def lateral_face(self) -> mod3d.TopoDS.Face:
        ...
    def lateral_start_wire(self) -> mod3d.TopoDS.Wire:
        ...
    def lateral_wire(self) -> mod3d.TopoDS.Wire:
        ...
    def meridian_closed(self) -> bool:
        ...
    def meridian_on_axis(self, v: typing.SupportsFloat) -> bool:
        ...
    def set_meridian_offset(self, meridian_offset: typing.SupportsFloat = 0.0) -> None:
        ...
    def shell(self) -> mod3d.TopoDS.Shell:
        ...
    def start_bottom_edge(self) -> mod3d.TopoDS.Edge:
        ...
    def start_edge(self) -> mod3d.TopoDS.Edge:
        ...
    def start_face(self) -> mod3d.TopoDS.Face:
        ...
    def start_top_edge(self) -> mod3d.TopoDS.Edge:
        ...
    def start_wire(self) -> mod3d.TopoDS.Wire:
        ...
    def top_edge(self) -> mod3d.TopoDS.Edge:
        ...
    def top_end_vertex(self) -> mod3d.TopoDS.Vertex:
        ...
    def top_face(self) -> mod3d.TopoDS.Face:
        ...
    def top_start_vertex(self) -> mod3d.TopoDS.Vertex:
        ...
    def top_wire(self) -> mod3d.TopoDS.Wire:
        ...
    @typing.overload
    def v_max(self) -> float:
        ...
    @typing.overload
    def v_max(self, v: typing.SupportsFloat) -> None:
        ...
    def v_max_infinite(self) -> bool:
        ...
    @typing.overload
    def v_min(self) -> float:
        ...
    @typing.overload
    def v_min(self, v: typing.SupportsFloat) -> None:
        ...
    def v_min_infinite(self) -> bool:
        ...
class Revolution(OneAxis):
    def __init__(self, A: mod3d.gp.Ax2, VMin: typing.SupportsFloat, VMax: typing.SupportsFloat, M: mod3d.Geom.Curve, PM: mod3d.Geom2d.Curve2d) -> None:
        """
        Create a revolution body. M is the meridian and must be in the XZ plane of A. PM is the meridian in the XZ plane.
        """
    def make_empty_lateral_face(self) -> mod3d.TopoDS.Face:
        """
        The surface normal should be directed towards the outside.
        """
    def make_empty_meridian_edge(self, Ang: typing.SupportsFloat) -> mod3d.TopoDS.Edge:
        """
        Returns an edge with a 3D curve made from the meridian in the XZ plane rotated by Ang around the Z-axis. Ang may be 0 or myAngle.
        """
    def meridian_value(self, V: typing.SupportsFloat) -> mod3d.gp.Pnt2d:
        """
        Returns the meridian point at parameter V in the plane XZ.
        """
    def set_meridian_pcurve(self, E: mod3d.TopoDS.Edge, F: mod3d.TopoDS.Face) -> None:
        """
        Sets the parametric curve of the edge E in the face F to be the 2d representation of the meridian.
        """
